# Generated by Django 5.1 on 2024-09-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_detailstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtype', models.CharField(max_length=255)),
                ('cardholdername', models.CharField(max_length=255)),
                ('cardnumber', models.CharField(max_length=16)),
                ('expirydate', models.CharField(max_length=255)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameModel(
            old_name='course_details',
            new_name='course_detailstable',
        ),
    ]
