# Generated by Django 5.1 on 2024-09-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('tname', models.CharField(blank=True, max_length=255, null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
