# Generated by Django 5.1 on 2024-09-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('skills', models.TextField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
