# Generated by Django 5.1 on 2024-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_login',
            fields=[
                ('email', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_signup',
            fields=[
                ('email1', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
