# Generated by Django 5.1 on 2024-09-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('skills', models.CharField(max_length=25)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=25)),
            ],
        ),
    ]
