# Generated by Django 4.2.16 on 2024-09-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_job_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=25)),
                ('resume', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='job_details',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
