# Generated by Django 5.1 on 2024-09-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_register',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_register',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student_register',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
